### ISSUE TITLE
Image loading VERY slow

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#121]
I am loading the same source (one of the Baldwin partbooks on beta and on the old site, and the images are coming up much more quickly on the old site. I've now been waiting several minutes for the first image to load here: https://beta.diamm.ac.uk/sources/2348/. When it does eventually load scrolling is delayed while a new image loads.

**Comment by belljustin** [comment]
Seems to involve a RangeError with diva. I'll investigate further

**Comment by ahankinson** [comment]
This is likely a problem with the images. @belljustin here is some more info:

There is a script that will take the image filenames and construct an 'info' request to the image server to get width/height information about the image. This is saved in the [iiif_response_cache](https://github.com/diamm/diamm/blob/master/diamm/models/data/image.py#L26) field on the image model.

If the server is unable to find the image, it will not be able to load the width/height info and store it in this field. The most likely source of this problem is that there is a mismatch between the filename in the database, and the filename of the actual image. Thus the width/height of the image will be 0, and Diva will be sad.

The way to fix this is to identify what the filename is that is causing the problem, and then check the images on the server to see what it's actually called. If you can't log in to check, you can just let me know the filename that is in the database, and I'll see if I can find something similar to it on the server.

**Comment by ahankinson** [comment]
@juliacmcf I don't think it's just very slow; for me the images are not loading at all. In the new viewer, if one image is misnamed (actual filename and database entry do not match) it will fail to load all the images. This *could* be changed, but for now I will leave it like this since it makes it very easy to determine problematic sources.

**Comment by ahankinson** [comment]
You can always do a sanity check against the old site by taking the number of the source (2348, in this case) and looking it up on the old site by replacing the number in the sourceKey. So:

http://www.diamm.ac.uk/jsp/Descriptions?op=SOURCE&sourceKey=2348

(@belljustin you might find this handy too.)

**Comment by ahankinson** [comment]
In this case, it looks like there's a problem with the 'pasted slip' image for this source. @juliacmcf you may want to look into this and make sure the filename matches in the database.

**Comment by belljustin** [comment]
Same issue with the 'pasted slip' in source GB-Och Mus. 983, pk: 2352

I suppose these manifests should be repaired anyway but are corrupted/missing images already being addressed in Diva? Seems like an issue that the viewer should be able to side-step (e.g. replace image with file not found but load all the rest)

For now, @jeromepl and I discussed just catching the error (RangeError) that results from a bad image and giving a user alert to that effect

**Comment by ahankinson** [comment]
See my comment above:

> In the new viewer, if one image is misnamed (actual filename and database entry do not match) it will fail to load all the images. This *could* be changed, but for now I will leave it like this since it makes it very easy to determine problematic sources.

**Comment by ahankinson** [comment]
In other words: The bug is a feature, at the moment, since it helps us track down problematic sources. If we just silently don't load page images, it's much harder to figure out if there is a problem.

**Comment by ahankinson** [comment]
Ongoing work to solve this; closing for now.
