### ISSUE TITLE
SourceProvenance has a region in it's country field

### ISSUE THREAD

**Issue by belljustin** [diamm/diamm#127]
England, as a `GeographicArea`, is a region but in the `SourceProvenance` model it is a country

This causes an issue in provenance integration with the source view because the link redirects to a view that filters `GeographicAreas` by country (of which England is apparently not a part)

Things to look into:
- We could change the country view such that it includes regions (though this seems a bit ingenuous)
- what is happening in the migration of `SourceProvenance` that's causing this?

**Comment by ahankinson** [comment]
The underlying region entry has to do with the migration of the `alProvenance` and the `alCountry` tables from Filemaker. The countries are migrated first, and then the provenance list. If a country name is not found, the entry in the provenance table gets converted into a geographic area as a "region." 

The way to fix that part is to ensure all entries that are countries in the provenance list also have an entry in the country list. For example, Japan is listed in the provenance table, but not in the country table so it gets a geographic area type of region. @juliacmcf will have to do this.

This doesn't solve the issue noted, but it is something that will need addressing. I'll keep looking into the issue.

**Comment by juliacmcf** [comment]
The main reason for this was to prevent countries where MSS originated but did not have any libraries did not turn up in the facet list as a country with no sub-headings. I have a feeling Japan is a red herring now: I had a Japanese MS of 4th-century Qin music, but removed it as it was silly (in the context).

**Comment by ahankinson** [comment]
In Filemaker, the 'country' key in SourceProvenance_IS points to an entry in the alProvenance table, not to an entry in the alCountry table. This is the underlying cause of the problem, since some entries in alProvenance are not countries ("Bohemia"). 

There are no easy fixes for this. The best would be to ensure that only 'countries' are in the country column in alProvenance, and then sub-divided by region. So the entry would be "Great Britain" for country, and then "England" for region. 

Of course, there are historical and political statements being made here, but I think we should err on the side of practicality over absolute correctness, for the following reasons:

1. The overriding consideration of this system of reference is co-location and cross-reference. That is, given a geographic area, what are all of the sources that are related to that geographic area, and what are all the subdivisions of the geographic area that also have source relationships. By unifying the provenance table and the other geographic region tables, I am trying to bring together different representations of space in the existing DIAMM data, while still allowing DIAMM cataloguers to enter things as they find them.

2. The political divisions (country / region / province, etc.) are not given temporal limits, so they should be assumed to be contemporary, not historical. Thus England (to take an example) is given the type "Region / Cultural Area" even though it has existed as a country on its own previously. This also lets us sidestep questions about the emergence of 'countries' (and not kingdoms or principalities): Was Scotland ever a country, or was it a kingdom? I really don't want to get into that.

**Comment by ahankinson** [comment]
Related: Should "Great Britain" be changed to "United Kingdom"? That one bugs me...

**Comment by juliacmcf** [comment]
It bugs me too, but I’m matching the RISM abbreviation, which is GB, even though almost everywhere else in the Universe it’s UK. Besides, we might not be a UK for much longer, and then everyone else will have to change to GB, or something.

**Comment by juliacmcf** [comment]
Would it help if I merged the alCountry and alProvenance tables in the FM database and pointed the intersection set from the source to the alCountry table? Maybe we could put something in a new field in alCountry to stop those records showing up in a list of libraries?

Incidentally, I have no idea where Bohemia actually is/was. Matthias can probably tell me.

**Comment by ahankinson** [comment]
By not listing countries, this is no longer an issue. Might come up again later, but by then we'll probably have a cleverer solution.
