### ISSUE TITLE
Bibliography entries

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#177]
I had difficulty in adding a new bibliography item as there was no place to insert information about the journal and the page span for the article. I had to stuff everything into the title line.

**Comment by ahankinson** [comment]
If you scroll down to the 'Additional Publication Info' section you will be able to add a number of fields:
 - "Title of Parent Entry"
 - "Volume"
 - "Pages"

and several others, which you should choose based on the type of source you are cataloguing. You can add as many of these as you like, but not all fields will appear in all entry types, i.e., entering a 'series number' for a dissertation won't make that information appear.

Putting all of the information in the title field should be avoided, since it won't format that properly (italics, etc.)

**Comment by juliacmcf** [comment]
Thanks. Just not used to the interface yet!
