### ISSUE TITLE
Problem dealing with contributor changes

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#182]
I just accepted a problem report and now can’t find it: searching on the list for either first or last name of contributor returns an error. I needed to know the MS the report referred to as I stupidly now only have the sourceKey (I can still get to his report via the email link, but that only shows the sourceKey and in the list of sources I can’t search on sourceKey only on name, and the name is only shown in the master issue list.). Sorry. Frustrated! Finally got to it by a roundabout route by changing the sourceKey in the website listing for Eton and found the name from that. Really need to be able to search in list of sources on SourceKey, not just shelfmark, as if I put the shelfmark in slightly wrong because I forgot to copy it to the clipboard from the main list (can't trust memory!), I won't find it. Also it would probably be good to see shelfmark as well as sourceKey in both the list view and the individual report -- please!

**Comment by ahankinson** [comment]
I've made a couple improvements to source key searching in the list of sources, but it's still not exact. The issue is that, to also support things like shelfmark searching, it needs to search the content of all the fields. So if you search for '202' as a source key, you will also get "fonds latin 7202" as a result.

The source key is available in the individual report; it's under "Object ID". This is given a generic name because this system is also set up to handle record reports from other types of records (composition, person, source, organization); there's just not a public interface for submitting them. So if it's a "person" record, the object id will refer to the person key; if it's a source record, object id will refer to the source key.

I've also made an improvement that the entity name (the source name, in this case) is now displayed in the individual record view. That change will come with the next site update.

**Comment by juliacmcf** [comment]
Need a separate search box! 

It will probably solve it just to have the source name appear in the report.

**Comment by ahankinson** [comment]
You should see the source name in the report now.

**Comment by juliacmcf** [comment]
Yaaay!
