### ISSUE TITLE
Oddity in source description

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#196]
In the screenshot attached the notation and surface notes appear twice, once at the top in the list of these things, and again under the main description. First screenshot is from GB-Lbl Add. MS 30513. In GB-Lbl Add. MS 29247 (second screenshot) there is a different issue with things that should be in the top list appearing below the description with big headings. Could this be because I'm logged in as an editor?

<img width="373" alt="screen shot 2017-05-25 at 17 04 57" src="https://cloud.githubusercontent.com/assets/10816169/26458895/8f478544-416c-11e7-8b73-aa662150c1be.png">
<img width="593" alt="screen shot 2017-05-25 at 17 13 47" src="https://cloud.githubusercontent.com/assets/10816169/26459209/9add183c-416d-11e7-84b5-6eee939d15fb.png">

**Comment by ahankinson** [comment]
This is because the information in the 'Surface' description has been transcribed also as a 'Surface' note.

Sources have a fixed set of possible surface types to aid in faceted search (we could limit search results by only those sources in a set that have a 'Parchment' surface, for example). These options are enumerated here: 

https://github.com/diamm/diamm/blob/master/diamm/models/data/source.py#L16-L32

There is also a Note type of "Surface". This is not intended to (as here) repeat the information in the surface field; rather, it's an opportunity for the cataloguer to expand on interesting qualities of the surface. "Vellum made from a really lovely cow" might be an example of a surface note.

In this case I think it's safe to either delete the surface note or expand the note with any particular observations on the surface that exist in the general description.

The same is true of foliation (https://github.com/diamm/diamm/blob/master/diamm/models/data/source.py#L39-L44) and notations, except that for notations the values of the field on the top are taken from the "Notations" table.

**Comment by ahankinson** [comment]
I just noticed, however, that 'Other Identifiers' should not appear. I'll file that as a separate bug.

**Comment by juliacmcf** [comment]
There’s an image-link bug in https://www.diamm.ac.uk/sources/394/#/ <https://www.diamm.ac.uk/sources/394/#/>

The image in the thumbnail preview is correct, but when you click on it you get something else.

**Comment by juliacmcf** [comment]
I don’t know where these notes came from… The few records I’ve looked at have quite a few errors — information in the wrong fields mostly, and that’s down to James doing a useless job (which is SO annoying), but those would have been uploaded, whereas additional notes should not be possible unless someone is putting them in, and I don’t think james has editing rights does he?

**Comment by juliacmcf** [comment]
I have looked at a couple of other source descriptions, and there are random notes duplicating what is in the main descriptive fields all over the place. See for example: D-AAm Chorbuch II (Mangon Choirbook II) <which for some random reason comes up first if I search for 'Paston Manuscripts'>

**Comment by ahankinson** [comment]
I'm going to close this because it's not an issue with the site, but with cataloguing practices.
