### ISSUE TITLE
Choose naming for libraries and archives

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#22]
would the 'Archive' label not more accurately be called 'Library/Archive'? There seem to be as many libraries as archives on your list of locations.

**Comment by mscuthbert** [comment]
Is "Institution" a good overarching category?

**Comment by juliacmcf** [comment]
Seems like a good general title to me. I can't think of anything better off the top of my head.

**Comment by juliacmcf** [comment]
Or 'Owner', because there are quite a few private collections (at least 20, maybe more) and it might seem odd to call them an institution; owner also emphasizes the ownership of the document. People might however find this odd in place of library/archive/institution.

**Comment by mscuthbert** [comment]
Owner is probably good for 95% of the time, but it would mean that Machaut Vg would need to be listed as "Kansas City, Ferrell" and not "Cambridge, Parker".  On the other hand, I know of at least two cases where switching to "Owner" would be more appropriate.  For instance, Trent, Biblioteca Comunale 1563, is owned by the Biblioteca Comunale but actually stored at "Trent, Castello Buon..."  (The other is Assisi, Bib. Com. 187, which is stored at the Bibl. Sacro. ... of St. Francis) 

This reminds me (if you're up for suggestions yet), I think that the heading of a manuscript page / search result should be in the form "Oxford, Bodleian Library, Canon. Misc. 213" and not "GB-Ob Canon. Misc. 213" and only use RISM sigla for linking when space is at a premium; given that we're using post-1980 RISM sigla now ("GB-Ob Canon. Misc 213" instead of "GB-Ob213") the space savings is far less than it used to be, compared to the clarity (and potentially higher Google search results)

**Comment by ahankinson** [comment]
I'll move that suggestion to a new issue and comment on it there.

**Comment by juliacmcf** [comment]
It seems this has opened a can of worms! The primary purpose of the library/archive label is to tell people where to find the MS if they want to look at it, so possibly 'location' would be most all embracing (country>city (and yes, lots of those places are not cities)>location). We have:
Libraries
Archives
record offices
private collections
MSS owned by one person/institution but kept in another institution/place (in addition to Myke's list, three Oxford college libraries have lodged some of their MSS in the Bodleian, and the same is true of some Cambridge Colleges and CUL)

**Comment by ahankinson** [comment]
It seems to me that the purpose of the label is not identify all the different types, but to identify a group of institutions notable for being hosts to items.

Personally I think Archives are a good collective name for this group. It is a fairly unambiguous name that represents the fact that it hosts collections. Institution might be confused with educational institutions, I.e. Harvard University instead of Harvard university libraries. Library may also be OK, but I think that MSS are better represented by name as being part of an archival collection.

Perhaps "collections" or "collectors" are the most accurate, but I also think it would require the most explanation. Just because something is accurate doesn't mean that it is understood. :)

**Comment by juliacmcf** [comment]
And of course 'archive' has sufficed without comment from any users for over a decade!

**Comment by ahankinson** [comment]
I am going to keep it as "Archive" for now. Please re-open if you disagree.
