### ISSUE TITLE
Figure out best way to import archives' former name

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#24]
Currently the archive have their 'former' name in their actual name. We should have a field to separate out the 'formerly' part of the name. Also, this name should be indexed for search.

**Comment by juliacmcf** [comment]
Do you want me to create a separate field in the old database (archive table), or just make sure the indication in the current archive field is consistent so that you can separate it out when you import to your system?

**Comment by ahankinson** [comment]
Either would work!

**Comment by ahankinson** [comment]
I've added it to the new website. I've assigned the task to you now, @juliacmcf . Will you have time to change this in Filemaker, or would you prefer if I tackled this on my end?

**Comment by juliacmcf** [comment]
No problem. Sorry for silence but all computers out of the house for TP open days this weekend!

**Comment by ahankinson** [comment]
@juliacmcf any news on this?

**Comment by juliacmcf** [comment]
Haven’t done it in the database, but that’s because I’ve been snowed under. I can look at it this week. It’s easy enough to do as so few libraries have former names, so I can just manually move the info into another field. Do you want to know the field name? I can call it formerName or something like that?

**Comment by juliacmcf** [comment]
fixing this in the old database now: field name is formerName in the Archive table.

**Comment by ahankinson** [comment]
OK, great. Will you just remove the former name from the name field? (If so then it won't make it to the old website, but I'm not sure how much of a concern that is now)

**Comment by juliacmcf** [comment]
Yes, I’ve removed it. Was just thinking that I could make the uploading field a calculated field that reinstates the former name explanation (i.e. '(formerly: …)’ but can be turned off to just leave the original name. Will this screw things up? If it will I can just leave the former names off for the next old-website upload.

**Comment by ahankinson** [comment]
It depends -- are we going to do another old website upload?

**Comment by juliacmcf** [comment]
I think we probably should, unless you don’t think it’s worth it? I suspect some people will prefer to continue using the old site until it is replaced with the new one, particularly if they hit a beta bug that prevents them from doing the one thing they might want to do!

I’ve just been sorting out several corrections that people have asked for and it might be nice to put those up, though I know it’s usually a nightmare of bug-fixing with my data…

**Comment by ahankinson** [comment]
At this point I think the interaction and data on the beta site is far superiour to the old site. The only things that are *not* on the beta site are the special projects, the 'about us' sections, and anything that is not centred around the data.

What I might do is update the beta site with a new database dump. The process of doing that is a lot easier and finds all the bugs in the data, so that we can then update the old site.

**Comment by juliacmcf** [comment]
In that case I think I will update from James’s new information (only about 150 records done so far) to see what that looks like in a description.

One note that I meant to make before but failed to do about source descriptions, but I will raise a new ticket for that one.

**Comment by juliacmcf** [comment]
This is now fixed in the FM database (new field: formerName)

**Comment by mscuthbert** [comment]
As we're thinking through this, I've found a persistent problem in my own catalog system is what changed in a former/olim field.  e.g., does "formerly" refer to, the archive's name has changed, or the manuscript moved from one archive to another?  Did the change in archive result in a change to the shelfmark at the same time?  A lot of these things are pretty easy to figure out, but https://beta.diamm.ac.uk/sources/62/ is hard -- did the change of call number coincide with the change in library name (Central -> Catalunya).

Some of the former archive/former owner Relationships are politically sensitive and should be checked before going live.  One big one is: https://beta.diamm.ac.uk/sources/760/  : "(owner) Imperial Library, St. Petersburg" -- I think that "owner" should be replaced with "former owner" or "owner/former owner", etc., because the ownership of some of these manuscripts is still in dispute, and I don't think DIAMM should be seen as taking sides.

I'll put a few more issues on archives that might be more thought items than directly connected here. Thanks!

**Comment by ahankinson** [comment]
Personally, I think situational information like a former shelfmark + former archive relationship is a significant enough corner case to not try and model it in the database, and instead give guidance to the cataloguer that it should be noted in a description field. The 'olim' field is really an aid to searching: I want to find a source that was referred to as 'x' in article 'y'.

**Comment by mscuthbert** [comment]
Sounds great!

**Comment by juliacmcf** [comment]
The former name for libraries only refers to a change in the library name. If a MS has moved there is (currently) a source record which redirects to the new location (including new shelf-mark if that has also changed).On 15 Jun 2016, at 15:26, Michael Scott Cuthbert <notifications@github.com> wrote:As we're thinking through this, I've found a persistent problem in my own catalog system is what changed in a former/olim field.  e.g., does "formerly" refer to, the archive's name has changed, or the manuscript moved from one archive to another?  Did the change in archive result in a change to the shelfmark at the same time?  A lot of these things are pretty easy to figure out, but https://beta.diamm.ac.uk/sources/62/ is hard -- did the change of call number coincide with the change in library name (Central -> Catalunya).Some of the former archive/former owner Relationships are politically sensitive and should be checked before going live.  One big one is: https://beta.diamm.ac.uk/sources/760/  : "(owner) Imperial Library, St. Petersburg" -- I think that "owner" should be replaced with "former owner" or "owner/former owner", etc., because the ownership of some of these manuscripts is still in dispute, and I don't think DIAMM should be seen as taking sides.I'll put a few more issues on archives that might be more thought items than directly connected here. Thanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
