### ISSUE TITLE
Archive record link

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#370]
When I clicked on the 'British Library' link at the top of a manuscript description I expected to see our info page for the library as I was looking for contact details for the music librarian. Instead it sent me straight through to the BL website, which has this information rather well buried! I would prefer that this link would take users to a DIAMM library page for each library, with all the contact information and the URL link for their own website there. I am not sure what happens for libraries that don't have a website (and there are still a few) -- I can't remember which ones they are so couldn't test it.

**Comment by ahankinson** [comment]
OK; should be an easy fix.

**Comment by ahankinson** [comment]
I just had a look, and I can't seem to replicate this. The logo links to our record of the BL (/archives/32) -- in fact, the information to get to the website isn't even available on the MSS description.

Can you provide the source you were looking at so I can confirm this? I tried Royal App. 49, since that was the one you filed the correction reports for, but that seems to be behaving correctly.

**Comment by juliacmcf** [comment]
I fixed this somehow — I changed the names of the flyleaves to roman numbers, which didn’t seem to make a difference (and the change doesn’t seem to have filtered through), then I added page links for a few of the pieces that didn’t have them and that seemed to fix it.

I notice that the other MSS in this set have no inventory, so I think this is a set that didn’t have one. The odd thing is that there is a linked inventory at all, and only in the first book. I can’t see how that would have got in, since if we did it at all we would have done it for all the books. This is a late acquisition.

Might just be one of those weird bugs that goes away by itself!

**Comment by juliacmcf** [comment]
This seems to have been mixed up with another problem report. The library page for any library is not displaying the information about the library, only the library name and a link to their website. Ideally all the library record information should come up on the library page (I just told someone to click on the library link to get contact details, and they got back to me to say there wasn't anything). At the moment you just get the library name and location, a link to their website, and a list of MSS in DIAMM. Since libraries hide contact information so well it would be most useful to get the address and contact information that we have put into the background record. It's not urgent, but a lot of useful data is invisible.

**Comment by ahankinson** [comment]
I seem to remember (maybe misremember?) that we talked about this way back, and decided against it. I believe the reason was that we weren't sure that all the contact information we had about the libraries was up-to-date and correct (the named person was no longer there, or the phone number / fax / e-mail didn't work?). There was also some private information about the library, but I think that's mostly in the private notes, so we don't have to show it...

**Comment by juliacmcf** [comment]
I think the address and contact email would be useful — I remember the hassle I had finding that information originally. Of course the websites are better now, but most of them still hide their postal addresses! We have people wanting to contact libraries for permission, so that stuff would be useful, but you’re right, definitely not everything! 

just the address and contact email should be sufficient. I have no doubt people will let us know if anything is wrong.

We have been putting big MSS into the database manually and have got a sort of production line going. There are two things though that would make an enormous difference to the speed of adding page records and linking images to them. Another report coming…
