### ISSUE TITLE
Weird search result

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#378]
If you put 'Trent 92' into the search box, you get some fairly irrelevant things...

**Comment by ahankinson** [comment]
Hm. All of the ones that aren't the actual Trent MSS mention Trent 92 in the descriptions.

**Comment by juliacmcf** [comment]
I thought that was it. Maybe the sorting of the results needs to prioritise MS shelf mark, or did doing that screw something else up?

**Comment by ahankinson** [comment]
Sorting is done based on 'relevance' so that the most relevant things pop to the top. In the case of a tie (each mss getting the same relevancy ranking) the sorting is effectively random. (In practice, it's more-or-less alphabetical). Shelfmarks are already weighted slightly more, but in practice it's hard to fine tune the search system -- what might work for one type of query will make other types of queries much worse.

**Comment by ahankinson** [comment]
This looks like it's been fixed.
