### ISSUE TITLE
Incorrect action when attributing record edits

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#413]
I'm presuming when I attribute a problem report to someone else, that attribution should be the one that appears in the live site (not me or whoever put in the report)? If so, it's not happening.

Meg Bent submitted a bibliographical item for one MS, with the note that it should be added to two others. I submitted problem reports for those two MSS as that seemed to be the only way to edit the content under the contributors tab (to acknowledge her), but when I accepted the problem report with Margaret Bent in the credit line, it was still attributed to me on the live site. I've worked around by putting 'submitted by Margaret Bent' in the summary.

**Comment by fattoxxon** [comment]
Another related 'issue': when a contributor is acknowledged, the text of the solution ("Summary") is added, but not what the contributor actually contributed ("Note" field, e.g. a statement of the problem). Consequently the contributor gets credited with fixing, rather than identifying, the problem; which is 'invisible unless re-stated in the 'solution' text. Neither is a big issue; but it does reduce the value/accuracy of including contributions on the source records.

**Comment by ahankinson** [comment]
If you click the magnifying glass next to the 'contributor' it will give you an opportunity to change the account linked to the contributions. Since most people will have accounts, this is the best way to do it.
