### ISSUE TITLE
Hide image tab for not logged in users

### ISSUE THREAD

**Issue by ahankinson** [diamm/diamm#61]
Still working out what to do here, but for now we'll just hide it if a user is not logged in.

**Comment by juliacmcf** [comment]
It is useful for people to know (whether logged in or not) whether we have images for a MS. If there's no tab it would be good to indicate this somewhere. At present the description field is set to insert a comment at the top of the description saying whether we have images or not (because we got so many angry users who couldn't see images and just didn't get that we didn't have images for everything): 
If ( done = "N" and webpermission = "N" ; "<strong><em>DIAMM does NOT yet have images of this manuscript.</em></strong>"  & ¶ ; "" ) & 
If ( done = "Y" and webpermission = "N" ; "<strong><em>DIAMM has images of this manuscript, but does not yet have permission to put them online.</em></strong>" & ¶ ; "" ) & 
If ( done = "Y" and webpermission = "Y" ; "<strong><em>Please click on the 'images' tab above (or scroll down) to view thumbnails of images of this manuscript. The thumbnails become live links to the full-size images only if you are logged in. If some of the thumbnails do not load please refresh/reload your browser page.</em></strong>" & ¶ ; "" )

**Comment by ahankinson** [comment]
Yeah, I just need to figure out how and where to place it on the page -- I'm thinking of putting a notice somewhere prominent that says you need to log in to view the images.

We already have this note appearing on the source pages, and the logic for it is here:

https://github.com/diamm/diamm/blob/master/diamm/templates/website/source/source_detail_block.jinja2#L123

**Comment by belljustin** [comment]
How about putting the notice under the sources' image tab? That way we can also give them a call to action -  via a link to register/login - exactly when they want to access this feature

**Comment by ahankinson** [comment]
I disabled the link to the images, and put a 'log in' link next to the images tab, as shown in the screenshot attached.

![diamm-61](https://cloud.githubusercontent.com/assets/163183/16650994/61dc7a7a-4441-11e6-8f43-f935393784be.png)
