### ISSUE TITLE
Browsable Interface for Cities, Archives, Manuscripts

### ISSUE THREAD

**Issue by juliacmcf** [diamm/diamm#96]
Would it be possible to get to e.g. a list of cities/libraries/manuscripts on the beta site? At the moment you can see nothing unless you search for something. However someone who puts in something that gets no results is then stuck. I know it's old hat, but people are of course used to drilling down into DIAMM via this route, and not having that old list view means you don't get the change to spot things in libraries or places that you might not get to know about otherwise. Just close this issue if this is already on your to-do list.

**Comment by ahankinson** [comment]
I'll keep this open. It is on the to-do list, but this will let us track progress towards it.

**Comment by ahankinson** [comment]
Echoing my comments from the commit -- I'm not sure a simple pagination list for manuscripts is useful, since many sources would just be ordered by their shelfmark, which doesn't really contain any identification across all libraries. For example, there would be five MSS that are named just "1".

People will be able to browse by city, then archive, then the MSS holdings of that archive, which would seem to me to be a more natural way of looking for it.
